@url_dev=http://localhost:3001/v1/api

## User signup
POST {{url_dev}}/auth/signup
Content-Type: application/json
x-api-key: 96954d273079ed28f1026ca4f5b6525285764d6e8101e6643033fdfa6a17d9303c284c0088438124d037032dd830b655318456a28365c2ef92d8c7386ea9adca

{
    "email": "nhanhxuan3@gmail.com",
    "password": "123456",
    "name": "Hanh Xuan"
}

###
## User login
POST {{url_dev}}/auth/signin
Content-Type: application/json
x-api-key: 96954d273079ed28f1026ca4f5b6525285764d6e8101e6643033fdfa6a17d9303c284c0088438124d037032dd830b655318456a28365c2ef92d8c7386ea9adca

{
    "email": "nhanhxuan3@gmail.com",
    "password": "123456"
}

###
## User refresh token
POST {{url_dev}}/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imhhbmh4dWFuMTgwNEBnbWFpbC5jb20iLCJpYXQiOjE2OTU2MzM4NzEsImV4cCI6MTY5NjIzODY3MX0.vAylQeoaX75UR5uQPSc7QwBqcRvZFwlgiZlckIVNtfQ"
}